(()=>{
'use strict';const H=window.HAKI;
H.setTool=t=>{H.tool=t;H.$$('.tool[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));const c=H.canvas;c.isDrawingMode=t==='draw';if(c.isDrawingMode){c.freeDrawingBrush.color='#fff';c.freeDrawingBrush.width=6}c.defaultCursor=t==='hand'?'grab':'default'};
H.addText=(x=300,y=300)=>{const o=H.addMeta(new fabric.IText('HAKI',{left:x,top:y,fill:'#fff',fontSize:72,fontWeight:'800',fontFamily:'Arial'}),'design','Texto');H.canvas.add(o).setActiveObject(o);H.snapshot();H.refresh()};
H.addRect=(x=300,y=300)=>{const o=H.addMeta(new fabric.Rect({left:x,top:y,width:280,height:180,fill:'#fff',stroke:'#000',strokeWidth:0}),'design','Rectángulo');H.canvas.add(o).setActiveObject(o);H.snapshot();H.refresh()};
H.addCircle=(x=300,y=300)=>{const o=H.addMeta(new fabric.Circle({left:x,top:y,radius:110,fill:'#fff',stroke:'#000',strokeWidth:0}),'design','Círculo');H.canvas.add(o).setActiveObject(o);H.snapshot();H.refresh()};
H.addPrintZone=(x=360,y=300)=>{const n=H.canvas.getObjects().filter(o=>o.hakiKind==='printzone').length+1,o=H.addMeta(new fabric.Rect({left:x,top:y,width:420,height:500,fill:'rgba(51,221,255,.06)',stroke:H.PRINT_COLOR,strokeWidth:3,strokeDashArray:[12,8],objectCaching:false}),'printzone','Zona '+n);H.canvas.add(o).setActiveObject(o);H.snapshot();H.refresh();H.toast('Zona de impresión creada')};
H.readImageFile=(file,kind)=>new Promise((res,rej)=>{const r=new FileReader();r.onerror=rej;r.onload=()=>fabric.Image.fromURL(r.result,img=>{if(!img){rej();return}const mw=H.canvas.getWidth()*(kind==='mockup'?.9:.55),mh=H.canvas.getHeight()*(kind==='mockup'?.9:.55),s=Math.min(mw/img.width,mh/img.height,1);img.set({left:H.canvas.getWidth()/2,top:H.canvas.getHeight()/2,originX:'center',originY:'center',scaleX:s,scaleY:s,globalCompositeOperation:'source-over'});H.addMeta(img,kind,kind==='mockup'?'Mockup':'Diseño');res(img)},{crossOrigin:'anonymous'});r.readAsDataURL(file)});
H.importFiles=async(files,kind)=>{const list=[...files];if(!list.length)return;H.status('Importando…');for(const f of list){try{const img=await H.readImageFile(f,kind);kind==='mockup'?H.canvas.insertAt(img,0,false):H.canvas.add(img);H.canvas.setActiveObject(img)}catch{H.toast('No pude abrir '+f.name)}}H.snapshot();H.refresh();H.fit();H.status('Listo');H.toast(kind==='mockup'?'Mockup añadido':'Imagen añadida')};
H.setObjectProp=()=>{const o=H.active();if(!o)return;const w=Math.max(1,+H.$('#pWidth').value||o.getScaledWidth()),h=Math.max(1,+H.$('#pHeight').value||o.getScaledHeight());o.set({left:+H.$('#pLeft').value||0,top:+H.$('#pTop').value||0,angle:+H.$('#pAngle').value||0,opacity:Math.max(0,Math.min(1,(+H.$('#pOpacity').value||0)/100)),skewX:+H.$('#pSkewX').value||0,skewY:+H.$('#pSkewY').value||0,globalCompositeOperation:H.$('#pBlend').value});if(o.width)o.scaleX=w/o.width;if(o.height)o.scaleY=h/o.height;if(typeof o.fill==='string')o.fill=H.$('#pFill').value;if('stroke'in o)o.stroke=H.$('#pStroke').value;o.strokeWidth=+H.$('#pStrokeWidth').value||0;o.setCoords();H.canvas.requestRenderAll()};
H.applyFilters=()=>{const o=H.active();if(!H.isImage(o))return;const F=fabric.Image.filters,v={brightness:+H.$('#fBrightness').value||0,contrast:+H.$('#fContrast').value||0,saturation:+H.$('#fSaturation').value||0,blur:+H.$('#fBlur').value||0};o.hakiFilters=v;o.filters=[];if(v.brightness)o.filters.push(new F.Brightness({brightness:v.brightness/100}));if(v.contrast)o.filters.push(new F.Contrast({contrast:v.contrast/100}));if(v.saturation)o.filters.push(new F.Saturation({saturation:v.saturation/100}));if(v.blur)o.filters.push(new F.Blur({blur:Math.min(.9,v.blur/110)}));o.applyFilters();H.canvas.requestRenderAll();Object.keys(v).forEach(k=>H.$('#'+k+'Value').textContent=v[k])};
H.duplicate=()=>{const o=H.active();if(!o)return;o.clone(c=>{c.set({left:(o.left||0)+30,top:(o.top||0)+30});H.addMeta(c,o.hakiKind||'design',H.objectName(o)+' copia');c.hakiFilters=o.hakiFilters?{...o.hakiFilters}:undefined;c.hakiMaskId=o.hakiMaskId||'';H.canvas.add(c).setActiveObject(c);H.snapshot();H.refresh()},['hakiFilters'])};
H.removeActive=()=>{const a=H.active();if(!a)return;if(a.type==='activeSelection')a.forEachObject(o=>H.canvas.remove(o));else H.canvas.remove(a);H.canvas.discardActiveObject();H.snapshot();H.refresh()};
H.layerMove=action=>{const o=H.active();if(!o)return;H.canvas[action](o);H.snapshot();H.refresh()};
H.applyMask=id=>{const o=H.active();if(!o||o.hakiKind==='printzone')return;o.hakiMaskId=id||'';if(!id){o.clipPath=null;H.snapshot();H.refresh();return}const z=H.canvas.getObjects().find(x=>x.hakiId===id);if(!z)return;o.clipPath=new fabric.Rect({left:z.left,top:z.top,width:z.width,height:z.height,scaleX:z.scaleX,scaleY:z.scaleY,angle:z.angle,skewX:z.skewX,skewY:z.skewY,originX:z.originX,originY:z.originY,absolutePositioned:true,fill:'#000'});H.snapshot();H.refresh();H.toast('Máscara aplicada')};
H.exportImage=()=>{const fmt=H.$('#exportFormat').value,m=+H.$('#exportScale').value||2,hide=H.$('#hideMockupExport').checked,hidden=[];H.canvas.getObjects().forEach(o=>{if(o.hakiKind==='printzone'||(hide&&o.hakiKind==='mockup')){hidden.push([o,o.visible]);o.visible=false}});H.canvas.discardActiveObject();H.canvas.renderAll();const data=H.canvas.toDataURL({format:fmt,quality:.94,multiplier:m,enableRetinaScaling:false});hidden.forEach(([o,v])=>o.visible=v);H.canvas.renderAll();H.downloadData(data,`HAKI-${Date.now()}.${fmt==='jpeg'?'jpg':'png'}`);H.toast('Exportación lista')};
H.downloadData=(data,name)=>{const a=document.createElement('a');a.href=data;a.download=name;a.click()};
})();
