(()=>{
'use strict';const H=window.HAKI;
H.downloadProject=()=>{const data=JSON.stringify({version:1,name:H.$('#projectName').value,canvas:H.canvas.toJSON(['hakiId','hakiKind','hakiName','hakiVisible','hakiMaskId','hakiFilters','selectable','evented'])});H.downloadData('data:application/json;charset=utf-8,'+encodeURIComponent(data),'HAKI-project.haki.json')};
H.importProject=async file=>{try{const d=JSON.parse(await file.text());H.restoring=true;H.canvas.loadFromJSON(d.canvas||d,()=>{H.restoring=false;H.canvas.renderAll();H.snapshot();H.refresh();H.fit();H.toast('Proyecto abierto')})}catch{H.toast('Proyecto no válido')}};
H.dbOpen=()=>new Promise((res,rej)=>{const q=indexedDB.open('haki-studio',1);q.onupgradeneeded=()=>q.result.createObjectStore('projects',{keyPath:'id'});q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)});
H.saveLocal=async()=>{try{const db=await H.dbOpen(),name=H.$('#projectName').value.trim()||'Proyecto HAKI',id=localStorage.getItem('haki-last-project')||H.uid(),item={id,name,updated:Date.now(),data:H.canvas.toJSON(['hakiId','hakiKind','hakiName','hakiVisible','hakiMaskId','hakiFilters','selectable','evented'])};await new Promise((res,rej)=>{const tx=db.transaction('projects','readwrite');tx.objectStore('projects').put(item);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});localStorage.setItem('haki-last-project',id);H.toast('Proyecto guardado en este dispositivo')}catch{H.toast('No se pudo guardar')}};
H.listLocal=async()=>{const db=await H.dbOpen();return new Promise((res,rej)=>{const q=db.transaction('projects').objectStore('projects').getAll();q.onsuccess=()=>res(q.result.sort((a,b)=>b.updated-a.updated));q.onerror=()=>rej(q.error)})};
H.showProjects=async()=>{const box=H.$('#savedProjects');box.innerHTML='Cargando…';H.$('#projectsModal').classList.add('open');try{const items=await H.listLocal();box.innerHTML=items.length?'':'No hay proyectos guardados.';items.forEach(it=>{const r=document.createElement('div');r.className='saved-row';r.innerHTML=`<div><strong>${H.escapeHtml(it.name)}</strong><small>${new Date(it.updated).toLocaleString()}</small></div><button>Abrir</button>`;r.querySelector('button').onclick=()=>{localStorage.setItem('haki-last-project',it.id);H.$('#projectName').value=it.name;H.restoring=true;H.canvas.loadFromJSON(it.data,()=>{H.restoring=false;H.canvas.renderAll();H.snapshot();H.refresh();H.fit();H.$('#projectsModal').classList.remove('open')})};box.appendChild(r)})}catch{box.textContent='No se pudieron leer los proyectos.'}};
})();
