(()=>{
'use strict';const H=window.HAKI;
H.bindUI=()=>{
 H.$$('.tool[data-tool]').forEach(b=>b.onclick=()=>H.setTool(b.dataset.tool));
 H.$('#designInput').onchange=e=>{H.importFiles(e.target.files,'design');e.target.value=''};H.$('#mockupInput').onchange=e=>{H.importFiles(e.target.files,'mockup');e.target.value=''};H.$('#projectInput').onchange=e=>{if(e.target.files[0])H.importProject(e.target.files[0]);e.target.value=''};
 H.$('#undoBtn').onclick=H.undo;H.$('#redoBtn').onclick=H.redo;H.$('#fitBtn').onclick=H.fit;H.$('#zoomIn').onclick=()=>H.zoomBy(1.2);H.$('#zoomOut').onclick=()=>H.zoomBy(1/1.2);H.$('#panelToggle').onclick=()=>H.$('#sidepanel').classList.toggle('open');
 H.$$('.tab').forEach(b=>b.onclick=()=>{H.$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');H.$$('.tabpage').forEach(x=>x.classList.remove('active'));H.$('#'+b.dataset.tab+'Page').classList.add('active')});
 ['pLeft','pTop','pWidth','pHeight','pAngle','pOpacity','pSkewX','pSkewY','pBlend','pFill','pStroke','pStrokeWidth'].forEach(id=>{H.$('#'+id).oninput=H.setObjectProp;H.$('#'+id).onchange=()=>{H.setObjectProp();H.snapshot();H.refresh()}});
 ['fBrightness','fContrast','fSaturation','fBlur'].forEach(id=>H.$('#'+id).oninput=()=>{H.applyFilters();clearTimeout(H.filterTimer);H.filterTimer=setTimeout(H.snapshot,220)});H.$('#resetFilters').onclick=()=>{['fBrightness','fContrast','fSaturation','fBlur'].forEach(id=>H.$('#'+id).value=0);H.applyFilters();H.snapshot();H.refresh()};
 H.$('#flipX').onclick=()=>{const o=H.active();if(o){o.set('flipX',!o.flipX);H.snapshot();H.refresh()}};H.$('#flipY').onclick=()=>{const o=H.active();if(o){o.set('flipY',!o.flipY);H.snapshot();H.refresh()}};H.$('#duplicate').onclick=H.duplicate;H.$('#delete').onclick=H.removeActive;
 H.$('#bringFront').onclick=()=>H.layerMove('bringToFront');H.$('#sendBack').onclick=()=>H.layerMove('sendToBack');H.$('#bringForward').onclick=()=>H.layerMove('bringForward');H.$('#sendBackward').onclick=()=>H.layerMove('sendBackwards');
 H.$('#newPrintZone').onclick=()=>H.addPrintZone(380,320);H.$('#maskSelect').onchange=e=>H.applyMask(e.target.value);H.$$('[data-blend]').forEach(b=>b.onclick=()=>{const o=H.active();if(o){o.set('globalCompositeOperation',b.dataset.blend);H.snapshot();H.refresh()}});
 H.$('#whiteBg').onclick=()=>{H.canvas.setBackgroundColor('#fff',H.canvas.renderAll.bind(H.canvas));H.snapshot()};H.$('#transparentBg').onclick=()=>{H.canvas.setBackgroundColor('rgba(0,0,0,0)',H.canvas.renderAll.bind(H.canvas));H.snapshot()};H.$('#resizeCanvas').onclick=()=>{H.canvas.setWidth(Math.max(100,+H.$('#canvasW').value||1200));H.canvas.setHeight(Math.max(100,+H.$('#canvasH').value||1200));H.snapshot();H.fit()};
 H.$('#textValue').oninput=()=>{const o=H.active();if(o?.type==='i-text'){o.set('text',H.$('#textValue').value);H.canvas.renderAll();H.markModified()}};H.$('#fontSize').oninput=()=>{const o=H.active();if(o?.type==='i-text'){o.set('fontSize',+H.$('#fontSize').value||60);H.canvas.renderAll();H.markModified()}};H.$('#fontWeight').onchange=()=>{const o=H.active();if(o?.type==='i-text'){o.set('fontWeight',H.$('#fontWeight').value);H.snapshot();H.refresh()}};H.$('#fontFamily').onchange=()=>{const o=H.active();if(o?.type==='i-text'){o.set('fontFamily',H.$('#fontFamily').value);H.snapshot();H.refresh()}};
 H.$('#applyWarp').onclick=H.applyWarp;H.$('#exportBtn').onclick=()=>H.$('#exportModal').classList.add('open');H.$('#doExport').onclick=()=>{H.exportImage();H.$('#exportModal').classList.remove('open')};H.$$('[data-close]').forEach(b=>b.onclick=()=>H.$('#'+b.dataset.close).classList.remove('open'));
 H.$('#saveLocal').onclick=H.saveLocal;H.$('#loadLocal').onclick=H.showProjects;H.$('#downloadProject').onclick=H.downloadProject;
 document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;const k=e.key.toLowerCase();if((e.ctrlKey||e.metaKey)&&k==='z'){e.preventDefault();e.shiftKey?H.redo():H.undo();return}if((e.ctrlKey||e.metaKey)&&k==='y'){e.preventDefault();H.redo();return}if((e.ctrlKey||e.metaKey)&&k==='d'){e.preventDefault();H.duplicate();return}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();H.removeActive();return}if(k==='v')H.setTool('select');if(k==='h')H.setTool('hand');if(k==='b')H.setTool('draw');if(k==='t')H.setTool('text')});
 window.addEventListener('resize',()=>setTimeout(H.fit,80));const ws=H.$('#workspace');['dragover','dragenter'].forEach(ev=>ws.addEventListener(ev,e=>e.preventDefault()));ws.addEventListener('drop',e=>{e.preventDefault();const imgs=[...e.dataTransfer.files].filter(f=>f.type.startsWith('image/'));if(imgs.length)H.importFiles(imgs,'design')});
};
})();
